@host=http://localhost:5231

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "johndeo@gmail.com",
    "password": "password"
}