@host=http://localhost:5231

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "Vichea",
    "lastName": "nath",
    "email": "ohndeo@gmail.com",
    "password": "password"
}