@host=http://localhost:5231

GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NzA0OTQ0Ny0wZDNiLTQwNDctODc2Zi04ZjVlMTkzOGQ5MTAiLCJnaXZlbl9uYW1lIjoiVmljaGVhIiwiZmFtaWx5X25hbWUiOiJuYXRoIiwianRpIjoiMjNjYjIzMTUtOTVjNS00ODFlLTkwMjktNDJiOGU5N2M0MGQwIiwiZXhwIjoxNzE0NDg4Njc2LCJpc3MiOiJCdWJlckRpbm5lciIsImF1ZCI6IkJ1YmVyRGlubmVyIn0.aiNXC3A2mvmt1xbL3bApDn2WBPHJSJEqbLj0Fj5t_gw